### ISSUE TITLE
relevant resource?

### ISSUE THREAD

**Issue by dinahhandel** [amiaopensource/analog-inspection#11]
Just saw Kara Van Malssen tweet this from AIC, wonder if/how it could fit into either this repo or another? https://github.com/antimodular/Best-practices-for-conservation-of-media-art 

Or maybe it is out of scope?

**Comment by kfrn** [comment]
I read this a while back and was trying to find it again! It's a great document.
I'm not sure if it is really in scope here, as he seems to be talking primarily about software-based work.
Maybe it's one to start off a new resource page?

**Comment by retokromer** [comment]
In my opinion, a new resource page would be a good solution.

**Comment by retokromer** [comment]
ping

**Comment by kfrn** [comment]
Shall I go ahead with creating a new repo for software-based preservation issues?

**Comment by retokromer** [comment]
I guess this would be the best solution.

**Comment by kfrn** [comment]
Will do. Do we want the focus on media art/software-based art specifically, or software in general?

**Comment by retokromer** [comment]
I personally would prefer on software in general, but I think the majority will support mainly software-based art.

Most probably, useful resources on software-based art have been published by my former students Patrícia Falcão and Agathe Jarczyk.

**Comment by retokromer** [comment]
I suggest we start with media/software-based art only, and expand in a second step to software in general if needed. Thoughts?

**Comment by kfrn** [comment]
I created a new repo for TBA/media art/software-based-art here: https://github.com/amiaopensource/software-based-art
So far I just threw a bunch of links in, it needs some more work! But it's a starting point.

**Comment by retokromer** [comment]
Thank you very much, @kfrn, this is indeed an excellent «starting point»!
