### ISSUE TITLE
administrative metadata

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/analog-inspection#23]
I just added administrative metadata to the open-workflows repository: https://github.com/amiaopensource/open-workflows/pull/68

And perhaps this repo would like to do the same? @kgrons, you are the original creator, how do you feel about also being a maintainer?

**Comment by retokromer** [comment]
Hmm… @kgrons or @kfrn (as in the Acknowledgements)?

**Comment by ablwr** [comment]
@kfrn provided the original list and @kgrons made the repo -- Kath(erine/ryn) combo power move, imo.

**Comment by retokromer** [comment]
Indeed, two is better than an alone maintainer.

**Comment by kgrons** [comment]
I'm in as maintainer! I'll submit a PR to add myself. 🤝

**Comment by kfrn** [comment]
I'll add  \myself as maintainer K2 :smile:

**Comment by ablwr** [comment]
Thanks y'all!

Would one of you mind adding the copyright and code of conduct reference too?

**Comment by kfrn** [comment]
Ash: I've added the CoC/copyright to my PR :grin:
