### ISSUE TITLE
Add resources to repo

### ISSUE THREAD

**Issue by kgrons** [amiaopensource/analog-inspection#4]
h/t to @ablwr 

Pull down all linked and add the files to the repo so we are less dependent on the external links.

**Comment by ablwr** [comment]
Thanks @kgrons! For context... there are a few linked files but it'd be better if we....

1 created a new folder
2 downloaded the files and put them in that folder
3 upload the folder and its contents

LOCKSS!

Ashley

**Comment by dinahhandel** [comment]
Super down to work on this on Friday post-symposium madness

**Comment by dinahhandel** [comment]
This has been done for all linked resources with available PDFs as of c393dfe. Some filenames were changed for clarity of where the PDF came from and directory structure was chosen based on organization of the forms in the readme.

**Comment by ablwr** [comment]
OMG AMAZING
